### ISSUE TITLE
Error in retrieving some backend data.

### ISSUE THREAD

**Issue by manolingam** [raid-guild/araboard#9]
![Annotation 2020-06-03 235206](https://user-images.githubusercontent.com/12480098/83725124-4700e400-a5f6-11ea-8b84-991a80b7548a.png)

**Comment by proofoftom** [comment]
Are there any javascript console logs you can report as well?

**Comment by manolingam** [comment]
Tried console logging but it worked this time. Will add the logs here if the same issue occurs again.
